version: "3"

services:

    # rabbitmq:
        # image: rabbitmq:3-management
        # # container_name: rabbit-nerdstore
        # environment:
            # RABBITMQ_USER: "vouviajar"
            # RABBITMQ_PASS: "vouviajar"

    # sql-server:
        # image: desenvolvedorio/nerdstore-sql-server:latest
        # container_name: nerdstore-sql-server
        # build: 
            # context: ../sql
            # dockerfile: ./Dockerfile
        # environment:
            # SA_PASSWORD: "MeuDB@123"
            # ACCEPT_EULA: "Y"     

    api-autenticacao:
        image: vouviajar/api-autenticacao:latest
        container_name: vouviajar-api-identidade    
        build: 
            context: ../src/Vouviajar.API.Autenticacao
            dockerfile: ./Dockerfile  
        restart: 
            always
        ports: 
           - "5100:5100"
        environment: 
            - aspnetcore_environment=production
            - aspnetcore_urls=http://*:5100
#        depends_on:
#            - rabbitmq
#            - sql-server
            
    vouviajar-server:
        image: vouviajar/vouviajar-server:latest
        container_name: vouviajar-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - api-autenticacao