// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VouViajar.Modulos.Eventos.Infrastructure.Persistence;

namespace VouViajar.Modulos.Eventos.Migrations
{
    [DbContext(typeof(EventoDbContext))]
    partial class EventoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VouViajar.Modulos.Eventos.Domain.Entities.Aggregates.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestinoIdLocalidade")
                        .HasColumnType("int");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrigemIdLocalidade")
                        .HasColumnType("int");

                    b.Property<string>("Resumo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SituacaoIdSituacao")
                        .HasColumnType("int");

                    b.Property<int?>("TipoIdTipo")
                        .HasColumnType("int");

                    b.Property<int>("TotalVagas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorVaga")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEvento");

                    b.HasIndex("DestinoIdLocalidade");

                    b.HasIndex("OrigemIdLocalidade");

                    b.HasIndex("SituacaoIdSituacao");

                    b.HasIndex("TipoIdTipo");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("VouViajar.Modulos.Eventos.Domain.Entities.Localidade", b =>
                {
                    b.Property<int>("IdLocalidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocalidade");

                    b.ToTable("Localidade");
                });

            modelBuilder.Entity("VouViajar.Modulos.Eventos.Domain.Entities.Situacao", b =>
                {
                    b.Property<int>("IdSituacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSituacao");

                    b.ToTable("Situacao");
                });

            modelBuilder.Entity("VouViajar.Modulos.Eventos.Domain.Entities.Tipo", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipo");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("VouViajar.Modulos.Eventos.Domain.Entities.Aggregates.Evento", b =>
                {
                    b.HasOne("VouViajar.Modulos.Eventos.Domain.Entities.Localidade", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoIdLocalidade");

                    b.HasOne("VouViajar.Modulos.Eventos.Domain.Entities.Localidade", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemIdLocalidade");

                    b.HasOne("VouViajar.Modulos.Eventos.Domain.Entities.Situacao", "Situacao")
                        .WithMany()
                        .HasForeignKey("SituacaoIdSituacao");

                    b.HasOne("VouViajar.Modulos.Eventos.Domain.Entities.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoIdTipo");

                    b.Navigation("Destino");

                    b.Navigation("Origem");

                    b.Navigation("Situacao");

                    b.Navigation("Tipo");
                });
#pragma warning restore 612, 618
        }
    }
}
